//TOKEN OBJECT
Metadata_APEX_CursoDev.tokenSObject();

//TOKEN FIELD
Metadata_APEX_CursoDev.tokenField();

//Schema Method
Metadata_APEX_CursoDev.schemaMethod();

//Two Ways
Metadata_APEX_CursoDev.describeResult();

//All Objects
Metadata_APEX_CursoDev.getAllObjects();

//All CustomObjects
Metadata_APEX_CursoDev.getAllCustomObjects()

//All info objects
Metadata_APEX_CursoDev.getAllCustomObjectsInfo();



